# check that a PR modified the correct files and nothing more
name: Check PR Files

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'ceremonies/**'

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR number
        run: echo "PR_NUMBER=$(jq --raw-output .number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Get changed files
        id: get-changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: Validate files
        run: |
          changed_files="${{ steps.get-changed-files.outputs.all }}"
          IFS=', ' read -r -a files <<< "$changed_files"
          
          if [[ ${#files[@]} -ne 3 ]]; then
            echo "More than 3 files have been changed"
            exit 1
          fi

          r1cs_files=($(grep -E '\.r1cs$' <<< "${files[@]}"))
          wasm_files=($(grep -E '\.wasm$' <<< "${files[@]}"))
          json_files=($(grep -E 'p0tionConfig\.json$' <<< "${files[@]}"))

          if [[ ${#r1cs_files[@]} -ne 1 || ${#wasm_files[@]} -ne 1 || ${#json_files[@]} -ne 1 ]]; then
            echo "Invalid or missing file extensions"
            exit 1
          fi

          directory_name="ceremonies/$(echo $GITHUB_HEAD_REF | sed -r 's/-ceremony$//')"

          for file in "${files[@]}"; do
            if [[ ! $file =~ ^$directory_name/ ]]; then
              echo "Files must be inside the $directory_name directory"
              exit 1
            fi
          done

          echo "All checks passed"
